name: bwu_emojione_iconset_svg
version: 0.1.2
description: SVG Emoji provided free by Emoji One packed as Polymer core-iconset
homepage: https://github.com/bwu-dart/bwu_emojione_iconset_svg
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  core_elements: ">=0.2.0 <0.8.0"
  paper_elements: ">=0.1.0+2 <0.8.0"
  polymer: '>=0.12.0+5 <0.17.0'
  path: '>=1.3.0 <1.4.0'

dev_dependencies:
  bwu_utils_dev: ^0.1.0-dev.9
  test: '>=0.12.2 <0.13.0'

transformers:
- polymer:
    entry_points:
    - example/example01.html
